name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: . # Path to the Dockerfile
          push: true
          tags: |
            briandev254/vividarts_studio:latest
            briandev254/vividarts_studio:${{ github.sha }}
            env:
              DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
              DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy application
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Add deployment commands here