name: Deploy

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: briandev254/vividarts_studio

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}



    

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: . # Path to the Dockerfile
      #     push: true
      #     tags: |
      #       briandev254/vividarts_studio:latest
      #       briandev254/vividarts_studio:${{ github.sha }}
      #   env:
      #       DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #       DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Deploy application
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   run: |
      #     # Add deployment commands here